Repository Naman-sharma00100/Introduction-webpage, pull requests merged in 2022-10, with the labels that each got.

#22 Update index.html
  index.html
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#24 Correct CSS file
  style.css
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#63 Update index.html
  index.html
Labels: spam

#79 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted
